# -*- coding: utf-8 -*-
"""luyệntập.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12jkz8ZRTr7xCT6SXNkjGS2TeeHSlJVqu
"""

n=int(input())
m=list(map(int,input().split()))
print(m)

"""B"""

n=int(input())
m=int(input())
c=n%m
print(c)

"""C"""

n=int(input())
m=int(input())
c=n//m
print(c)

"""D"""

import math
x=float(input())
a=math.tan(x)
print('%0.3f'%math.cos(x),'%0.3f'%math.sin(x),'%0.3f'%a,'%0.3f'%(1/a))

"""E"""

n=int(input())
if n%2==0:
    print("YES")
else:
    print("NO")

"""F"""

import math
n = int(input())
if math.sqrt(n) == int(math.sqrt(n)): # ở đây có nghĩa là xét xem có phải = số int hay không
    print("YES")
else:
    print("NO")

"""G"""

a=float(input())
b=float(input())
if a==0 and b!=0:
    print('vo nghiem')
else:
    print('%0.3f'%(-b/a))

"""H"""

import math
n=int(input())
print('%0.3f'%(math.sqrt(n)))

"""I"""

a,b,c=map(int,input().split())
x=max(a,b,c)
y=min(a,b,c)
print(y,x)

"""J"""

import math
a,b,c=map(int,input().split())
if a==math.sqrt(b**2+c**2) or b==math.sqrt(a**2+c**2) or c==math.sqrt(a**2+b**2):
    print("YES")
else:
    print("NO")

"""ĐỒ THỊ HÀM SỐ"""

import numpy as np
import matplotlib.pyplot as plt

# Tạo một mảng gồm 100 giá trị nằm đều nhau từ -1 đến 1
x = np.linspace(-1, 1, 100)

# Tính giá trị của hàm số y = x^2 + sqrt(1) + sinh(x)
y = x**2 + np.sqrt(1) + np.sinh(x)

# Vẽ đồ thị
plt.plot(x, y)

# Đặt nhãn cho trục x và trục y
plt.xlabel('x')
plt.ylabel('y')

# Hiển thị đồ thị
plt.show()

a=[5,7,3,2,9]
for i in a:
  print(i)

"""3 ĐIỂM THẲNG HÀNG"""

x=[]
y=[]
for _ in range(3):
    xi,yi=map(int,input().split())
    x.append(xi);y.append(yi)
if ((int(y[2])-int(y[0]))*(int(x[1])-int(x[0])))==(int(y[1])-int(y[0]))*(int(x[2]-int(x[0]))):
    print("YES")
else:
    print("NO")

"""NHẬP XUẤT MẢNG

"""

n=int(input())
y=list(map(int,input().split()))
print(*y)

"""**phần tử lớn nhất **"""

n=int(input())
y=list(map(int,input().split()))
c=max(y)
print(c)

name=str(input())
age=int(input())
print('xin chào tên tôi là {} tôi {} tuổi'.format(name,age))

# các phần tử dương
n = int(input())
m = list(map(int, input().split()))
# tạo biến chứa phần tử dương trong mảng
ptd = []
#duyệt phần tử dương trong mảng
for i in m:
    if i > 0:
        ptd.append(i)
#kiểm tra trường hợp kh có ptd
if len(ptd)!=0 :
    print(len(ptd))
    print(*ptd)
else :
    print('Day so khong co phan tu duong')

# các phần tử dương
n = int(input())
m = list(map(int, input().split()))

# khởi tạo biến tổng tránh giá trị rác
tong = 0

# tạo biến chứa phần tử dương trong mảng
ptd = []

#duyệt phần tử dương trong mảng
for i in m:
    if i > 0:
        tong += 1
        ptd.append(i)
#kiểm tra trường hợp kh có ptd
if len(ptd):
    print(tong)
    print(*ptd)
else :
    print('Day so khong co phan tu duong')